// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1IhorH110Pm9rA_KsDh6p9D1c1qa1suY',
    appId: '1:191442553786:web:8da90b8740cb20e07f6b83',
    messagingSenderId: '191442553786',
    projectId: 'chatapp-c14a1',
    authDomain: 'chatapp-c14a1.firebaseapp.com',
    storageBucket: 'chatapp-c14a1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXm5BGzt96xmzJjgwnOpo7qPSoBI74AT4',
    appId: '1:191442553786:android:6370e6d83f8428e27f6b83',
    messagingSenderId: '191442553786',
    projectId: 'chatapp-c14a1',
    storageBucket: 'chatapp-c14a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsI9yCAXK93z-25Ze1gwPzUxYBcfGY9UY',
    appId: '1:191442553786:ios:6e32145ac90969d87f6b83',
    messagingSenderId: '191442553786',
    projectId: 'chatapp-c14a1',
    storageBucket: 'chatapp-c14a1.appspot.com',
    iosBundleId: 'com.ChatApp.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsI9yCAXK93z-25Ze1gwPzUxYBcfGY9UY',
    appId: '1:191442553786:ios:6e32145ac90969d87f6b83',
    messagingSenderId: '191442553786',
    projectId: 'chatapp-c14a1',
    storageBucket: 'chatapp-c14a1.appspot.com',
    iosBundleId: 'com.ChatApp.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1IhorH110Pm9rA_KsDh6p9D1c1qa1suY',
    appId: '1:191442553786:web:d28a64ddf038c20a7f6b83',
    messagingSenderId: '191442553786',
    projectId: 'chatapp-c14a1',
    authDomain: 'chatapp-c14a1.firebaseapp.com',
    storageBucket: 'chatapp-c14a1.appspot.com',
  );

}